### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Melozzola** [canhnt/sne-xacml#2]
Hi, I would like to know if this project is still active and supported?
I would also like to understand if there is any plan to support all the specs.
If you need collaboration I might be able to help but I would need to understand if it is possible and how much effort is required to add the missing features.
Thank you

**Comment by canhnt** [comment]
Hi @Melozzola,

Thank you for your interests. However the project was not active anymore. You can fork and extend as needed.

With kind regards,
Canh.
